/// <reference types="@cloudflare/workers-types" />

// Custom worker entry. WebSocket upgrades can't pass cleanly through the Next.js
// (OpenNext) handler, so we intercept the room API at the raw-worker layer and
// forward it to the RoomDO Durable Object; everything else goes to Next.
//
// wrangler bundles this file (transpile-only). It's intentionally thin glue and
// is not type-checked (the DO in src/server/room-do.ts is).

// @ts-expect-error - generated by `opennextjs-cloudflare build` before deploy
import openNextHandler from "./.open-next/worker.js";
import { RoomDO } from "./src/server/room-do";

// Re-exported so the Durable Object class is included in the deployed bundle.
export { RoomDO };

// /api/room/<code> and /api/room/<code>/ws
const ROOM_PATH = /^\/api\/room\/([^/]+)(?:\/(ws))?$/;
const CODE_RE = /^[A-Z0-9]{4,12}$/; // lenient guard; the client validates strictly

interface WorkerEnv {
  ROOM_DO: DurableObjectNamespace;
  // OpenNext handler receives the full env; keep it opaque here.
  [key: string]: unknown;
}

export default {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const match = url.pathname.match(ROOM_PATH);

    if (match) {
      const code = match[1].toUpperCase();
      if (!CODE_RE.test(code)) {
        return new Response(JSON.stringify({ error: "bad_code" }), {
          status: 400,
          headers: { "content-type": "application/json" },
        });
      }
      const stub = env.ROOM_DO.get(env.ROOM_DO.idFromName(code));
      return stub.fetch(request);
    }

    // Everything else → Next.js via OpenNext.
    return openNextHandler.fetch(request, env, ctx);
  },
};
